export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const GET_LIBRARY_BEGIN = "GET_LIBRARY_BEGIN";
export const GET_LIBRARY_SUCCESS = "GET_LIBRARY_SUCCESS";
export const GET_LIBRARY_ERROR = "GET_LIBRARY_ERROR";

export const GET_BOOKSHELVES_BEGIN = "GET_BOOKSHELVES_BEGIN";
export const GET_BOOKSHELVES_SUCCESS = "GET_BOOKSHELVES_SUCCESS";
export const GET_BOOKSHELVES_ERROR = "GET_BOOKSHELVES_ERROR";

export const GET_BOOKSHELF_BEGIN = "GET_BOOKSHELF_BEGIN";
export const GET_BOOKSHELF_SUCCESS = "GET_BOOKSHELF_SUCCESS";
export const GET_BOOKSHELF_ERROR = "GET_BOOKSHELF_ERROR";

export const ADD_TO_LIBRARY = "ADD_TO_LIBRARY";
export const REMOVE_FROM_LIBRARY = "REMOVE_FROM_LIBRARY";

export const ADD_TO_BOOKSHELF = "ADD_TO_BOOKSHELF";